### ISSUE TITLE
Chapter 2 - Analyzing Twitter - twitteR package deprecated. should i switch to rtweet?

### ISSUE THREAD

**Issue by priyaII** [dipanjanS/learning-social-media-analytics-with-r#1]
Geoff who maintains TwitteR package mentioned - 

"This is the start of a relatively leisurely deprecation period for twitteR, in favor of using rtweet. Please start looking to switch over to that package. If you have any questions contact myself or @mkearney" 

Should I be concerned?

https://github.com/geoffjentry/twitteR

**Comment by raghavbali** [comment]
@priyaII TwitteR has been a popular and robust package which has remained one the favorites for analyzing Twitter for a long time now (thanks to Geoff for the wonderful work).

My take would be __not to worry__ about the issue till there are any breaking changes in Twitter API which may not land up in twitteR. 

_____

PS :  Also, rtweet is another wonderful package, their interfaces/utilities are quite similar to TwitteR and migrating to this shouldn't be a big hassle (if you choose to do so)

**Comment by mkearney** [comment]
If you have any questions about rtweet or if you spot any missing functionality be sure to let me know! In related news, I managed to secure a new domain for the rtweet package documentation website: http://rtweet.info/. So, things are getting pretty exciting over on the rtweet side of things :)

**Comment by dipanjanS** [comment]
@priyaII Thanks for bringing this to our notice, a really good find definitely. Like @raghavbali said unless Twitter makes any breaking changes to their API, it shouldn't be a problem for the time being. But the ultimate goal would definitely be to migrate this code such that we can use the latest package which is `rtweet`.

@mkearney The initial look at your package and the new website (congrats on getting it up and running!) looks promising, just wanted to know your recommendation on should we look at migrating our code base w.r.t twitter mining from leveraging the `twitteR` package to the `rtweet` package sometime in the future?

**Comment by mkearney** [comment]
Ohhh you'll have to forgive me. For some reason I thought I was tagged on a twitteR issue (which happens a lot actually), but on my second visit I finally picked up on the obvious context that you all have a working/maintaining a book on such things.

As to your question, I think absolutely you should. I'm not going away anytime soon and rtweet would certainly benefit from a wider use base- plus, I'm willing to help R users get what they want from Twitter but I can't really do that until they start giving rtweet a try. But I know how much work goes into into these kinds of things, I won't pressure you :).

**Comment by raghavbali** [comment]
@mkearney : Thanks for your inputs and the amazing work you are doing with rtweets. Will surely give it a try and come up with updates to this code base sometime in future. Cheers 👍 

@priyaII : Closing this issue/discussion. Feel free to share any feedback or questions regarding the book or otherwise.
