### ISSUE TITLE
Question regarding Flickr code

### ISSUE THREAD

**Issue by jl5000** [dipanjanS/learning-social-media-analytics-with-r#3]
Hi,

I'm a bit confused about lines 39-45 in your Flickr code; specifically I can't see how the token credentials in line 43 are being used by the GET/sprintf functions. Sorry, I'm still trying to figure things out.

**Comment by raghavbali** [comment]
Hi @jl5000 ,
Thanks for pointing out. Seems like token credentials aren't required in the calls after all. I have checked the API documentation as well to confirm the same.

You can safely ignore the token credential parameter and sorry for the confusion. I'll also update the code.

Do let us know if there's any other issue. Hope this solves the confusion.

Cheers

**Comment by jl5000** [comment]
Thanks for getting back to me. I'm currently trying to write my own script for accessing my own photosets, which are all set to be private. Your code works for me for anything public, but I suspect I need to begin messing with Access Tokens to access my own private content from the API.

**Comment by raghavbali** [comment]
@jl5000 your own content should be accessible using the ```photosets.getPhotos``` API endpoint, but of course you would need to make an authenticated call. Setting the parameter ```privacy_filter``` should do the trick. Checkout the official flickr API documentation for further details.

We can have a separate discussion in case you need any specific help. We would be glad to know if and how the code/examples on this repo were of help.
