### ISSUE TITLE
Questions for the chapter4 Istanbul data

### ISSUE THREAD

**Issue by dichika** [dipanjanS/learning-social-media-analytics-with-r#4]
Hi,
I am studying chapter4 and have two questions.

1. The meaning of levels_to traverse

It looks like the same operation is repeated for the number of levels_to_traverse in the code.
There seems to be no explanation about the traverse.
Would you tell me why we need to specify **levels_to_traverse** ?

2. Mistakes in the code?

- The line below are needed? It seems that sum_points are not used in other parts.

https://github.com/dipanjanS/learning-social-media-analytics-with-r/blob/master/Chapter%204%20-%20Analyzing%20Foursquare/Code/B06056_04_02_code.R#L126

- At this line, we should specify file_level1 instead of file_level2?

https://github.com/dipanjanS/learning-social-media-analytics-with-r/blob/master/Chapter%204%20-%20Analyzing%20Foursquare/Code/B06056_04_02_code.R#L129

Thanks.

**Comment by tusharshar** [comment]
Hi Dichika,

1. levels_to_traverse is used to determine how many hops from the city center you want to traverse to collect data. If you do more hops you will cover more geographical area and hence more data. In the code we are looking for new centers in each hop and looking for data around those centers.

2.  a. You are right sum_points is not used in other part. It was sort of a diagnostic variable at development time to keep track of how many points were generated as part of data collection process.
b. This one is a typo and the file should be file_level1 as you pointed out. I will fix these mistakes with a code push.

**Comment by dichika** [comment]
Thank you for your reply.

As for Q1, I understand the meaning of levels_to_traverse.
Based on your answer, it is expected that the center is updated according to the levels_to_traverse.
However, the information of the levels_to_traverse (that is **j**) does not seem to be used in the code.
The line below reflects your intension?
https://github.com/dipanjanS/learning-social-media-analytics-with-r/blob/master/Chapter%204%20-%20Analyzing%20Foursquare/Code/B06056_04_02_code.R#L119

**Comment by tusharshar** [comment]
It is not being directly but it governs the number of times the loop is run. Each time the loop is run we will generate new centers based on centers existing in the list. This if repeated 1 times gives you one hop from the center, if repeated 2 times you will get centers which are a result of spanning an arc from each of these centers so on and so forth. The variable level_to_traverse is used to control how many times you want to repeat the process.

**Comment by dichika** [comment]
Thank you for your concise reply.
I realized the meaning of the repeat with reading your explanation and executing the code.
