### ISSUE TITLE
Chpt. 2 mapCountry

### ISSUE THREAD

**Issue by 31michaelodonnell** [dipanjanS/learning-social-media-analytics-with-r#7]
Hi! 
Thank you so much for loading your code and sharing the work that you put into creating this book. 
I was working through the code and I was having some problems with mapCountry function. It might be a simple fix that I'm overlooking, but I would appreciate it if you could check out the screenshot and let me know what you think. Thank you! 

![image](https://user-images.githubusercontent.com/64817403/81026780-43d4d580-8e49-11ea-9476-b480655167d0.png)

**Comment by raghavbali** [comment]
Hi @31michaelodonnell 

We are glad you found our book/code useful.
Coming to the issue mentioned, the error is from [line 131](https://github.com/dipanjanS/learning-social-media-analytics-with-r/blob/aef8c32c29ff25911a7782acdddd31ed2ecec528/Chapter%202%20-%20Analyzing%20Twitter/Code/B06056_02_02_code.R#L131). 

Resolution would be first load the mapCountry function in memory. The function is available [here](https://github.com/dipanjanS/learning-social-media-analytics-with-r/blob/aef8c32c29ff25911a7782acdddd31ed2ecec528/Chapter%202%20-%20Analyzing%20Twitter/Code/B06056_02_02_code.R#L37).
Let us know if this works.

**Comment by 31michaelodonnell** [comment]
It worked! Thank you!!

**Comment by raghavbali** [comment]
Cool. Closing this for now.
